### ISSUE TITLE
Why valueOf ?

### ISSUE THREAD

**Issue by mihai-vlc** [stephenplusplus/is-stream-ended#1]
Just curios why do you call the `valueOf` method on the result.

``` js
return Boolean(ended).valueOf();
```

Isn't Boolean(val) returning the same thing ?

**Comment by stephenplusplus** [comment]
I'm not sure it matters, but I did it to avoid returning the Boolean object as opposed to just the `true` or `false` value:

```
> b = new Boolean(true)
undefined
> b2 = true
undefined

> typeof b
'object'
> typeof b2
'boolean'
```

**Comment by mihai-vlc** [comment]
I see, thank you !
From what I saw that only happens when you make a new instance of the Boolean object.
